# Project
version=21.2
group=net.darkhax.enchdesc
java_version=21

# Mod
mod_name=EnchantmentDescriptions
mod_author=Darkhax
mod_id=enchdesc
mod_license=LGPL 2.1
mod_description=Adds descriptions of enchantment effects to their descriptions.
mod_repo=https://github.com/Darkhax-Minecraft/Enchantment-Descriptions
mod_docs=https://docs.darkhax.net/mods/enchantment-descriptions/
mod_item_icon=minecraft:enchanted_book

# Build Flags
mod_client_only=true

# Common
minecraft_version=1.21.2
minecraft_version_range=[1.21.2, 1.22)
neo_form_version=1.21.2-20241022.151510
parchment_minecraft=1.21.1
parchment_version=2024.11.17
prickle_version=21.2.1

# NeoForge
neoforge_version=21.2.1-beta
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.106.1+1.21.2
fabric_loader_version=0.17.2

# CurseForge
curse_project=250419
curse_page=https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

# Modrinth
modrinth_project=UVtY3ZAC
modrinth_page=https://modrinth.com/mod/enchantment-descriptions

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false