modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues"
license="LGPL-2.1"

[[mods]]
modId="enchdesc"
updateJSONURL="https://updates.blamejared.com/get?n=enchantmentdescriptions&gv=1.16.2"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.enchdesc]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.enchdesc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="CLIENT"
	
[[dependencies.enchdesc]]
    modId="bookshelf"
    mandatory=true
    versionRange="[7,)"
    ordering="AFTER"
    side="CLIENT"