modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues"

[[mods]]
modId = "enchdesc"
version = "26.1.2.0"
displayName = "EnchantmentDescriptions"
updateJSONURL = "https://updates.blamejared.com/get?n=enchdesc&gv=26.1.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions"
logoFile = "logo_enchdesc.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Adds descriptions of enchantment effects to their descriptions."

[[mixins]]
config = "enchdesc.common.mixins.json"

[[mixins]]
config = "enchdesc.neoforge.mixins.json"

[[dependencies.enchdesc]]
modId = "minecraft"
type = "required"
versionRange = "26.1"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchdesc]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchdesc]]
modId = "prickle"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

